application: you-app-name-here
version: 1
runtime: python27
api_version: 1

threadsafe: true

default_expiration: "30d"

handlers:
- url: /
  static_files: frontend/index.html
  upload: frontend/index.html
  expiration: "15m"

- url: /(.*)
  script: backend.QuickSetup.app
  
