application: quicksetup-me
version: 1
runtime: python27
api_version: 1

threadsafe: true

handlers:
- url: /
  static_files: frontend/index.html
  upload: frontend/index.html

- url: /(.*)
  script: backend.QuickSetup.app
  
